const spaceCities = [
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/2.jpg',
    id: '',
    uuid: 1,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/4.jpg',
    id: '',
    uuid: 2,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/5.jpg',
    id: '',
    uuid: '3',
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/7.jpg',
    id: '',
    uuid: '4',
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/9.jpg',
    id: '',
    uuid: 5,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/6.jpg',
    id: '',
    uuid: 6,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/3.jpg',
    id: '',
    uuid: 7,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/1.jpg',
    id: '',
    uuid: 8,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/8.jpg',
    id: '',
    uuid: 9,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/10.jpg',
    id: '',
    uuid: 10,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/11.jpg',
    id: '',
    uuid: 11,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: '',
    cover_image_url: './space/12.jpg',
    id: '',
    uuid: 12,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
]

export default spaceCities
