const vintageCities = [
  {
    title: '',
    activities_count: '',
    name: 'Vienna',
    cover_image_url: './vintage/2.png',
    id: 1,
    uuid: 1,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: 'Sydney',
    cover_image_url: './vintage/4.png',
    id: 2,
    uuid: 2,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: 'Malmö',
    cover_image_url: './vintage/5.png',
    id: 3,
    uuid: '3',
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: 'Roma',
    cover_image_url: './vintage/7.png',
    id: '4',
    uuid: '4',
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: 'Londra',
    cover_image_url: './vintage/9.png',
    id: 5,
    uuid: 5,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: 'Lisbona',
    cover_image_url: './vintage/6.png',
    id: 6,
    uuid: 6,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
  {
    title: '',
    activities_count: '',
    name: 'New York',
    cover_image_url: './vintage/3.png',
    id: 7,
    uuid: 7,
    reviews_avg: 'reviews',
    description: 'description',
    operational_days: 'operational_days',
    city: 'City',
    retail_price: {
      value: 'retail_price value',
    },
  },
]

export default vintageCities
